#!/bin/sh
set -eu

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" \
  --set=api_password="$TEAM_WIKI_API_DB_PASSWORD" \
  --set=publish_password="$TEAM_WIKI_PUBLISH_DB_PASSWORD" \
  --set=classify_password="$TEAM_WIKI_CLASSIFY_DB_PASSWORD" \
  --set=reconcile_password="$TEAM_WIKI_RECONCILE_DB_PASSWORD" <<-'SQL'
CREATE ROLE team_wiki_api LOGIN NOINHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION PASSWORD :'api_password';
CREATE ROLE team_wiki_publish LOGIN NOINHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION PASSWORD :'publish_password';
CREATE ROLE team_wiki_classify LOGIN NOINHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION PASSWORD :'classify_password';
CREATE ROLE team_wiki_reconcile LOGIN NOINHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION PASSWORD :'reconcile_password';
SQL
